[package]

name = "rust-nes-emulator"
version = "0.1.0"
authors = ["Ben Fan <benjaminfan.github.io>"]
edition = "2021"

[features]
default = [ "unsafe-opt" ]
unsafe-opt = []


[dependencies]
sdl2 = "0.32"
log = "0.4.11"
tokio = {version = "0.2", features = ["uds"]}

[profile.release]
opt-level = 3
